# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/kirin710-9-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter sydneyi,$(TARGET_DEVICE)),)

endif
